In [1]:
import numpy as np

In [2]:
liste = np.array( [[1,2], [3,4]])
liste[ :, 1 ]

array([2, 4])

In [4]:
liste = np.array( [1,1,2,2])
np.where( liste == 1)

(array([0, 1]),)

In [6]:
np.arange(liste.size)

array([0, 1, 2, 3])